# docker-compose.yml
services:
  wiki-frontend:
    container_name: valorant-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_VALORANT_API_URL=${NEXT_PUBLIC_VALORANT_API_URL}
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_VALORANT_API_URL=${NEXT_PUBLIC_VALORANT_API_URL}
    restart: unless-stopped